# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TagsListViewComparison' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TagsListViewComparison


  pod 'TagListView', '~> 1.0'
  pod 'RangeSeekSlider', '~> 1.8'
  pod 'ObjectMapper', '~> 3.4'


end
